Update project
airi-industrial-ai/gnn-cloud-manufacturing pull request #1
Opened 2023-11-07 17:19 UTC by lewinskydmitry

1) Pre-commit, poetry, dvc were added
2) Naive solver was created
3) Notebook with solving problems using naive solver

2023-11-08 10:31 UTC, vpozdnyakov requested changes

2023-11-08 10:31 UTC, vpozdnyakov commented on .dvc/config
> +['remote "myremote"']
я не знаю что это, но если твое личное, то лучше убрать

2023-11-08 10:31 UTC, vpozdnyakov commented on .gitignore
> +/data
давай данные все таки оставим в репо

2023-11-08 10:31 UTC, vpozdnyakov commented on cloudmanufacturing/data.py
> +        map(int, "-".join(sheet_name.split(",")).split("-"))
обычно длинные тексты пишут в двойных кавычках, служебные строки в одинарных

2023-11-13 07:51 UTC, lewinskydmitry commented on cloudmanufacturing/data.py
> +        map(int, "-".join(sheet_name.split(",")).split("-"))
Думаю, что тут автокорректор на свое усмотрение так поправил. Принципиально ли возвращать назад?

2023-11-13 07:52 UTC, lewinskydmitry commented on .gitignore
> +/data
dvc тогда просто удалю и оставим данные как есть

2023-11-13 07:52 UTC, lewinskydmitry commented on .dvc/config
> +['remote "myremote"']
Это конфигурация облачного хранилища, ее не будет теперь, поскольку мы убираем dvc

2023-11-15 23:54 UTC, closed without merging